platform :ios, '11.0'

target 'Sakai-Example' do
  use_frameworks!
  pod 'Sakai', :path => '../'

  target 'Tests' do
    inherit! :search_paths
    pod 'Sourcery', '0.17.0'
    pod 'Require', '2.0.0'
    pod 'Quick', '2.2.0'
    pod 'Nimble', '8.0.5'
  end
end

post_install do |installer_representation|
    # Set Swift version to 5.0
    installer_representation.pods_project.targets.each do |target|
      if ['Result'].include? target.name
        target.build_configurations.each do |config|
          config.build_settings['SWIFT_VERSION'] = '5.0'
        end
      end
    end
end
