platform :ios, '10.0'

target 'Sakai-Example' do
  use_frameworks!
  pod 'Sakai', :path => '../'

  target 'Tests' do
    inherit! :search_paths
    pod 'Sourcery', '0.13.1'
    pod 'Require', '2.0.0'
    pod 'Quick', '1.3.0'
    pod 'Nimble', '7.1.1'
  end
end
